version: '3.7'

services:
  gestionesagre-yarp-utility:
    container_name: yarp-utility
    restart: always
    build:
      context: .
      dockerfile: src/GestioneSagre.Balancer/Dockerfile
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net